### ISSUE TITLE
Getting error "ValueError: Error when checking : expected conv2d_1_input to have shape (None, 300, 300, 1) but got array with shape (1, 260, 300, 1)"

### ISSUE THREAD

**Issue by pranky89** [jgv7/CNN-HowManyFingers#1]
Here is the error that i see during the run:

Using TensorFlow backend.
2017-08-30 21:39:15.459984: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-30 21:39:15.460147: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-30 21:39:15.460186: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-30 21:39:15.460219: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
init done
opengl support available
Traceback (most recent call last):
  File "application.py", line 136, in <module>
    main()
  File "application.py", line 84, in main
    pred = classes[np.argmax(model.predict(img)[0])]
  File "/home/pankaj/vev/lib/python3.5/site-packages/keras/models.py", line 913, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/home/pankaj/vev/lib/python3.5/site-packages/keras/engine/training.py", line 1695, in predict
    check_batch_axis=False)
  File "/home/pankaj/vev/lib/python3.5/site-packages/keras/engine/training.py", line 144, in _standardize_input_data
    str(array.shape))
**ValueError: Error when checking : expected conv2d_1_input to have shape (None, 300, 300, 1) but got array with shape (1, 260, 300, 1)**

**Comment by Adm28** [comment]
replace line 45 in application.py
 x0, y0, width = 200,180,300
